{% set name = "pypng" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/drj11/pypng/-/package_files/46033928/download
  sha256: f12da57353b7f3924a2b1c7f35a932ae806ae1bc0e54f8d7a546e7d5b45965e7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - png

about:
  home: https://gitlab.com/drj11/pypng/
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'Pure Python PNG image encoder/decoder'

extra:
  recipe-maintainers:
    - hmaarrfk
