{% set name = "pypng" %}
{% set version = "0.20220715.0" %}
{% set sha256 = "739c433ba96f078315de54c0db975aee537cbc3e1d0ae4ed9aab0ca1e427e2c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - png
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/drj11/pypng/
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Pure Python PNG image encoder and decoder
  description: PNG module for Python. PyPNG is written entirely in Python.
  dev_url: https://gitlab.com/drj11/pypng/
  doc_url: https://gitlab.com/drj11/pypng/-/blob/main/README.md


extra:
  recipe-maintainers:
    - hmaarrfk
